[package]
name = "tm_light_is_where"
version = "0.1.0"
authors = ["Jonathan Nilsson <jonathan@voysys.se>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
tm-rs = { path = "../tm-rs/tm-rs"}
tm-derive = { path = "../tm-rs/tm-derive" }
